name: Upload secrets
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install requirements
      run: |
        cd ./status
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt
    - name: Generate report
      run: |
        cd ./status
        python3 --version
        python3 env_test.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        CUSTOM_ACTOR: ${{ secrets.CUSTOM_ACTOR }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDED_USERS: ${{ secrets.EXCLUDED_USERS }}
        INCLUDED_USERS: ${{ secrets.INCLUDED_USERS }}
        STAT_UPLOAD_URL: ${{  secrets.STAT_UPLOAD_URL }}
        EXCLUDE_FORKED_REPOS: true
        EXCLUDE_ARCHIVED_REPOS: true
