name: Upload secrets
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: upload
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{
          "access_token": "'"${ACCESS_TOKEN}"'",
          "custom_actor": "'"${CUSTOM_ACTOR}"'",
          "excluded": "'"${EXCLUDED}"'",
          "excluded_langs": "'"${EXCLUDED_LANGS}"'",
          "excluded_users": "'"${EXCLUDED_USERS}"'",
          "exclude_forked_repos": "'"${EXCLUDE_FORKED_REPOS}"'"
        }' "$STAT_UPLOAD_URL"
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        CUSTOM_ACTOR: ${{ secrets.CUSTOM_ACTOR }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        STAT_UPLOAD_URL: ${{  secrets.STAT_UPLOAD_URL }}
